### ISSUE TITLE
Issue with Python 3 - AttributeError: 'bytes' object has no attribute 'read'

### ISSUE THREAD

**Issue by lr59** [F5Networks/bigsuds#9]
Hi - running Python 3, I receive decode errors whenever I try to make a call using the latest bigsuds version (1.0.6 on Python 3.6.3). Are you able to take a look? Thanks.

```python
>>> from bigsuds import BIGIP
>>> b = BIGIP("<device>", username=username, password=password)

>>> b.System.SystemInfo.get_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt2/python3/lib/python3.6/site-packages/bigsuds.py", line 379, in __getattr__
    client = self._client_creator('%s.%s' % (self._name, attr))
  File "/opt2/python3/lib/python3.6/site-packages/bigsuds.py", line 183, in _create_client
    self._timeout,self._port)
  File "/opt2/python3/lib/python3.6/site-packages/bigsuds.py", line 284, in get_client
    cache=cachedir, transport=transport, timeout=timeout)
  File "/opt2/python3/lib/python3.6/site-packages/suds/client.py", line 115, in __init__
    self.wsdl = reader.open(url)
  File "/opt2/python3/lib/python3.6/site-packages/suds/reader.py", line 151, in open
    d = self.fn(url, self.options)
  File "/opt2/python3/lib/python3.6/site-packages/suds/wsdl.py", line 159, in __init__
    self.build_schema()
  File "/opt2/python3/lib/python3.6/site-packages/suds/wsdl.py", line 220, in build_schema
    self.schema = container.load(self.options)
  File "/opt2/python3/lib/python3.6/site-packages/suds/xsd/schema.py", line 92, in load
    child.open_imports(options)
  File "/opt2/python3/lib/python3.6/site-packages/suds/xsd/schema.py", line 301, in open_imports
    imported = imp.open(options)
  File "/opt2/python3/lib/python3.6/site-packages/suds/xsd/sxbasic.py", line 581, in open
    result = self.download(options)
  File "/opt2/python3/lib/python3.6/site-packages/suds/xsd/sxbasic.py", line 597, in download
    d = reader.open(url)
  File "/opt2/python3/lib/python3.6/site-packages/suds/reader.py", line 78, in open
    d = self.download(url)
  File "/opt2/python3/lib/python3.6/site-packages/suds/reader.py", line 95, in download
    content = fp.read()
AttributeError: 'bytes' object has no attribute 'read'


>>> import bigsuds
>>> bigsuds.__version__
'1.0.6'
```

**Comment by lr59** [comment]
Worked it out :)

For future reference - turns out somehow ended up with both suds-jurko and suds-py3 installed. Uninstalling suds-jurko and then forcing a reinstall of suds-py3 has got it working.
